apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
nameSuffix: -local
resources:
  - ../../../base/users-service
  - secret.yaml
patches:
  - target:
      kind: Deployment
      name: users-service
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 1
