env: "dev"

grpc:
  host: "0.0.0.0"
  port: "50053" 

http:
  host: "0.0.0.0"
  port: "50083"

postgres:
  url: "postgres://administrator:administrator@users-db:5432/profiles?sslmode=disable"

s3:
  endpoint: "http://minio:9000"   
  root_user: "administrator"
  root_password: "administrator"
  bucket: "avatars"
  presign_ttl: "10m"            
  public_base_url: "http://localhost:9000"

avatar:
  max_size_bytes: 5242880 # 5 MiB
  allowed_content_types: ["image/jpeg", "image/png", "image/webp"]

timeouts:
  service: "5s"                    