apiVersion: apps/v1
kind: Deployment
metadata:
  name: users-service
  namespace: news
spec:
  template:
    spec:
      containers:
      - name: app
        args: [] 
        env:
          - name: ENV
            value: "prod"
          - name: GRPC_HOST
            value: "0.0.0.0"
          - name: GRPC_PORT
            value: "50053"
          - name: HTTP_HOST
            value: "0.0.0.0"
          - name: HTTP_PORT
            value: "50083"
          - name: POSTGRES
            valueFrom: { secretKeyRef: { name: users-secrets, key: POSTGRES } }
          - name: S3_ENDPOINT
            value: "https://s3.example.com"
          - name: S3_ROOT_USER
            valueFrom: { secretKeyRef: { name: users-secrets, key: S3_ROOT_USER } }
          - name: S3_ROOT_PASSWORD
            valueFrom: { secretKeyRef: { name: users-secrets, key: S3_ROOT_PASSWORD } }
          - name: S3_BUCKET
            value: "avatars"
          - name: S3_PRESIGN_TTL
            value: "10m"
          - name: S3_PUBLIC_BASE_URL
            value: "https://cdn.example.com"
          - name: AVATAR_MAX_SIZE_BYTES
            value: "5242880"
          - name: AVATAR_ALLOWED_CONTENT_TYPES
            value: "image/jpeg,image/png,image/webp"
          - name: TIMEOUTS_SERVICE
            value: "5s"
        volumeMounts: []  
      volumes: []         
