env: "dev"

grpc:
  host: "0.0.0.0"
  port: "50051"

http:
  host: "0.0.0.0"
  port: "50081"

auth:
  jwt_secret: "dev-secret-key"
  access_token_ttl: 15m
  refresh_token_ttl: 720h
  issuer: auth-service
  audience: ["api-gateway"]

db:
  db_url: "postgres://administrator:administrator@auth-db:5432/auth?sslmode=disable"

redis:
  redis_url: "redis://administrator:administrator@redis-db:6379/0"

timeouts:
  service: 5s