name: Auth-service CD

on:
  push:
    branches: [ main ]
    tags: [ 'v*' ]
    paths:
      - 'auth-service/**'
      - '.github/workflows/auth-cd.yml'
  workflow_dispatch:
    inputs:
      push_image:
        description: "Push image to GHCR?"
        type: choice
        options: [ "false", "true" ]
        default: "false"
      image_suffix:
        description: "Optional image name suffix (e.g. -test)"
        required: false
        default: "-test"

concurrency:
  group: cd-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read
  packages: write

env:
  BASE_IMAGE_NAME: ghcr.io/${{ github.repository_owner }}/go-news-aggregator/auth-service

jobs:
  docker-publish:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup QEMU (multi-arch)
        uses: docker/setup-qemu-action@v3

      - name: Setup Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Docker meta (tags & labels)
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            ${{ env.BASE_IMAGE_NAME }}${{ github.event_name == 'workflow_dispatch' && inputs.image_suffix || '' }}
          tags: |
            type=raw,value=latest,enable=${{ github.ref == 'refs/heads/main' }}
            type=ref,event=tag
            type=sha
          labels: |
            org.opencontainers.image.source=${{ github.repository }}
            org.opencontainers.image.revision=${{ github.sha }}

      - name: Build & Push
        uses: docker/build-push-action@v6
        with:
          context: auth-service
          file: auth-service/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: ${{ github.event_name != 'workflow_dispatch' || inputs.push_image == 'true' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha,scope=auth-service
          cache-to: type=gha,mode=max,scope=auth-service


